
describe('quizz can be administered by teacher and student can take part in it', () => {
    before(() => {
        cy.task("queryDb", "DROP TABLES classrooms, launched_quizzes, user_quizzes, users;").then(result => {
            console.log("dropped tables classrooms, launched_quizzes, user_quizzes and users")
        })
        cy.task("queryDb", "CREATE TABLE classrooms (uniqueclassroomid INT UNSIGNED NOT NULL AUTO_INCREMENT,classroomjson json,classroomowneruid VARCHAR(50), PRIMARY KEY(uniqueclassroomid));").then(result => {
            console.log("recreated classrooms table")
        })
        cy.task("queryDb", "CREATE TABLE user_quizzes (userquizzid INT UNSIGNED NOT NULL AUTO_INCREMENT,launchedquizid INT UNSIGNED NOT NULL,uid VARCHAR(50), answersjson json, PRIMARY KEY(userquizzid));").then(result => {
            console.log("recreated user_quizzes table")
        })
        cy.task("queryDb","CREATE TABLE launched_quizzes (launchedquizid INT UNSIGNED NOT NULL AUTO_INCREMENT,uniqueclassroomid INT UNSIGNED NOT NULL, quiz_state ENUM('IN_PROGRESS', 'IN_REVIEW', 'REVIEWED') NOT NULL, quizjson json, PRIMARY KEY(launchedquizid));"
        ).then(result => {
            console.log("recreated launched_quizzes")
        })
        cy.task("queryDb", "CREATE TABLE users (uid VARCHAR(50),userjson json);").then(result => {
            console.log("recreated users table")
        })
        cy.clearLocalStorageSnapshot()
        cy.clear_mysql_and_indexedDB()
    })
    beforeEach(() => {
        cy.restoreLocalStorage()
    })
    afterEach(() => {
        cy.saveLocalStorage()
    })
    it('teacher creates a classroom, a set of questions, and a quiz based on the set of questions', () => {
        cy.teacher_login()
        cy.add_classrooms(["cypress testing class"])
        let questionsArray = ["quiz question 1", "quiz question 2", "quiz question 3", "quiz question 4", "quiz question 5"]
        cy.add_quizz(questionsArray, "Quiz Number 1")
        cy.get('#__next > div > div > div > div > div:nth-child(1)')
        .findByRole('button', { name: /edit/i}).wait(3000).click()
        cy.findByRole('button', { name: /back/i}).click()
        cy.findByTestId('MenuIcon').click()
        cy.findByText(/my classrooms/i).click()
        cy.get('.MuiPaper-root > :nth-child(3)').click()
        cy.get(':nth-child(2) > .MuiPaper-root > .css-covv7-MuiGrid-root > .css-18zbpha-MuiGrid-root > .MuiButton-root').click()
        cy.get('#mui-42').type('launched quiz 1')
        cy.get('.MuiGrid-root > .MuiPaper-root').get('.PrivateSwitchBase-input').click()
        cy.findByRole('button', { name: /next/i}).click()
        cy.findByRole('button', { name: /launch/i}).click()
        cy.get(':nth-child(3) > .MuiPaper-root > .css-covv7-MuiGrid-root > .css-18zbpha-MuiGrid-root > .MuiButton-root').click()
        cy.get('.MuiTypography-h5').contains('launched quiz 1')
        cy.get('[data-testid="ArrowBackIcon"]').click()
        cy.get('[data-testid="ArrowBackIcon"]').click()
        cy.findByTestId('MenuIcon').click()
        cy.findByTestId('LogoutIcon').click()        
    })
    it('logs in as student and registers into classroom', () => {
        cy.student_login('hello2@cypress.io')
        cy.findByRole('button', {  name: /add/i}).click()
        cy.get('#__next > div > header > div').contains('Join a Classroom')
        cy.findByRole('textbox', {  name: /enter the teacher\-provided classroom code/i}).type('1')
        cy.findByRole('textbox', {  name: /enter a description for this classroom/i}).type('my joined classroom')
        cy.findByRole('button', {  name: /next/i}).click()
        cy.findByRole('button', {  name: /finish/i}).click()
        cy.get('.MuiButton-root').click()
        cy.get('.css-18zbpha-MuiGrid-root > .MuiButton-root').click()
        cy.get('.MuiButton-root').click()
        cy.get('h2').contains('Quiz Number 1')
        cy.findByRole('button', { name: /start quiz/i}).click()
        cy.findByRole('heading', {  name: /quiz question 1/i})
        cy.findByRole('textbox', {  name: /your answer/i}).type('student answer 1')
        cy.findByRole('button', {  name: /submit answer/i}).click()
        cy.findByRole('heading', {  name: /quiz question 2/i})
        cy.findByRole('textbox', {  name: /your answer/i}).clear().type('student answer 2')
        cy.findByRole('button', {  name: /submit answer/i}).click()
        cy.findByRole('heading', {  name: /quiz question 3/i})
        cy.findByRole('textbox', {  name: /your answer/i}).clear().type('student answer 3')
        cy.findByRole('button', {  name: /submit answer/i}).click()
        cy.findByRole('heading', {  name: /quiz question 4/i})
        cy.findByRole('textbox', {  name: /your answer/i}).clear().type('student answer 4')
        cy.findByRole('button', {  name: /submit answer/i}).click()
        cy.findByRole('heading', {  name: /quiz question 5/i})
        cy.findByRole('textbox', {  name: /your answer/i}).clear().type('student answer 5')
        cy.findByRole('button', {  name: /submit answer/i}).click()
        cy.findByText(  /you've answered all the question and you can submit the quiz/i)
        cy.findByRole('button', {  name: /submitquiz/i}).click()
        cy.findByText(/congratulations\. the quiz is submitted/i)
        cy.findByRole('button', {  name: /menu/i}).click()
        cy.findByText(/my classrooms/i).click()
        cy.findByRole('button', {  name: /open/i}).click()
        cy.findByRole('button', {  name: /view results/i}).click()
        cy.get('#__next > div > div:nth-child(2) > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)').contains(/questions answered/i)
        cy.get('[data-testid="ArrowBackIcon"]').click()
        cy.get('[data-testid="ArrowBackIcon"]').click()
        cy.get('#__next > div > header > div').contains('My Classrooms')
        cy.findByTestId('MenuIcon').click()
        cy.findByTestId('LogoutIcon').click()  
    })
    it('logins as teacher to check progress of launched quiz', () => {
        cy.teacher_login(true)
        cy.get('.MuiPaper-root > :nth-child(3)').click()
        cy.get(':nth-child(4) > .MuiPaper-root > .css-covv7-MuiGrid-root > .css-11sq1o7-MuiGrid-root > .MuiButton-root').click()
        cy.findByText(/classroom results/i)
        cy.get('.MuiAccordionSummary-content > .MuiTypography-root').contains(/questions answered/i)
        cy.get('#__next > div > div:nth-child(2) > div > div > div > div:nth-child(2) > div').contains('firstname2 lastname2')
        cy.end()
    })
})  