# Use root/example as user/password credentials
version: "3.1"

volumes:
  dbdata:
services:
  db:
    container_name: quizngaged-mysql
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 2051:3306
    environment:      
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password