-- MySQL Script generated by MySQL Workbench
-- Wed 26 Jan 2022 08:37:01 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `institutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `institutions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `institutions` (
  `institution_id` INT NOT NULL AUTO_INCREMENT,
  `institution_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`institution_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `institution_id` INT NULL,
  `is_teacher` TINYINT(1) NOT NULL DEFAULT 0,
  `is_student` TINYINT(1) NOT NULL DEFAULT 0,
  `is_parent` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_institutions_idx` (`institution_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzes` (
  `quiz_id` INT NOT NULL AUTO_INCREMENT,
  `teacher_user_id` INT NOT NULL,
  `quiz_type` ENUM('ENGAGEMENT', 'FEEDBACK', 'TEST') NOT NULL,
  `quiz_title` VARCHAR(255) NOT NULL,
  `quiz_topic` VARCHAR(255) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`quiz_id`),
  INDEX `fk_quizzes_users_idx` (`teacher_user_id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `question_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question_answers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `question_answers` (
  `answer_id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `display_order` INT NOT NULL,
  `answer_text` VARCHAR(255) NOT NULL,
  `matched_pair_answer_id` INT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_answers_questions_idx` (`question_id` ASC) VISIBLE,
  INDEX `fk_answers_matches_idx` (`matched_pair_answer_id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question_text` VARCHAR(255) NOT NULL,
  `question_type` ENUM('CHOOSE', 'TRUE-FALSE', 'SORT', 'MATCH-PAIRS', 'FREE-TEXT') NOT NULL,
  `variant_for_question_id` INT NULL,
  `correct_answer_id` INT NULL,
  `correct_sort_or_pairs` VARCHAR(255) NULL,
  `difficulty_level` ENUM('BASE', 'EASIER', 'HARDER') NOT NULL,
  `assigned_score` DECIMAL(5,2) NULL,
  `time_limit_seconds` INT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_questions_answers_idx` (`correct_answer_id` ASC) VISIBLE,
  INDEX `fk_questions_variants_idx` (`variant_for_question_id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quiz_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quiz_events` (
  `quiz_event_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `quiz_type` ENUM('ENGAGEMENT', 'FEEDBACK', 'TEST') NOT NULL,
  `quiz_state` ENUM('IN_PROGRESS', 'IN_REVIEW', 'REVIEWED') NOT NULL,
  `quiz_title` VARCHAR(255) NOT NULL,
  `quiz_topic` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`quiz_event_id`),
  INDEX `fk_events_quizzes_idx` (`quiz_id` ASC) VISIBLE);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `event_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_questions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `event_questions` (
  `event_question_id` INT NOT NULL AUTO_INCREMENT,
  `quiz_event_id` INT NOT NULL,
  `time_limit_seconds` INT NULL,
  `elapsed_to_cut_off_seconds` INT NULL,
  `average_score` DECIMAL(5,2) NULL,
  `uses_speed_of_response` TINYINT(1) NOT NULL DEFAULT 0,
  `uses_weighted_scoring` TINYINT(1) NOT NULL DEFAULT 0,
  `uses_class_average` TINYINT(1) NOT NULL DEFAULT 0,
  `question_snapshot` JSON NULL,
  INDEX `fk_event_questions_quiz_idx` (`quiz_event_id` ASC) VISIBLE,
  PRIMARY KEY (`event_question_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `student_quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_quizzes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `student_quizzes` (
  `quiz_event_id` INT NOT NULL,
  `student_user_id` INT NOT NULL,
  PRIMARY KEY (`quiz_event_id`, `student_user_id`),
  INDEX `fk_student_quizzes_idx` (`student_user_id` ASC) VISIBLE);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `student_responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_responses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `student_responses` (
  `quiz_event_id` INT NOT NULL,
  `student_user_id` INT NOT NULL,
  `event_question_id` INT NOT NULL,
  `given_answer_id` INT NULL,
  `given_sort_or_pairs` VARCHAR(255) NULL,
  `given_answer_text` VARCHAR(255) NULL,
  `raw_score` DECIMAL(5,2) NULL,
  `averaged_score` DECIMAL(5,2) NULL,
  `teacher_adjustment` DECIMAL(5,2) NULL,
  `time_taken_seconds` INT NULL,
  PRIMARY KEY (`quiz_event_id`, `student_user_id`, `event_question_id`),
  INDEX `fk_student_response_questions_idx` (`event_question_id` ASC) VISIBLE,
  INDEX `fk_student_response_quiz_event_idx` (`quiz_event_id` ASC, `student_user_id` ASC) VISIBLE,
  INDEX `fk_student_response_answers_idx` (`given_answer_id` ASC) VISIBLE);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quiz_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_questions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quiz_questions` (
  `quiz_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`quiz_id`, `question_id`),
  INDEX `fk_questions_questions_idx` (`question_id` ASC) VISIBLE,
  INDEX `fk_questions_quizzes_idx` (`quiz_id` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_relations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_relations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_relations` (
  `first_user_id` INT NOT NULL,
  `second_user_id` INT NOT NULL,
  `relationship` ENUM('PARENT', 'SUPERVISOR', 'TEACHER') NOT NULL,
  PRIMARY KEY (`first_user_id`, `second_user_id`),
  INDEX `fk_users_second_users_idx` (`second_user_id` ASC) VISIBLE,
  INDEX `fk_users_first_users_idx` (`first_user_id` ASC) VISIBLE);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
